
spring:
  application:
    name: api-gateway
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
zuul:
  routes:
    service-hi:
      path: /service-hi/
      serviceId: ceshi
